master:
  image: gettyimages/spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./target/scala-2.10/:/tasks

task:
  image: gettyimages/spark
  command: /usr/spark/bin/spark-submit --class com.quintor.EvaluateOutlierDetectionDistributed --master spark://master:7077 /tmp/app/target/scala-2.10/QuintorSparkOutlier-assembly-1.0.jar 1000 1 OutlierObservations /tmp/results/memoryser2.txt
  links:
    - master
    - kafka
    - zookeeper
  volumes:
    - ./results:/tmp/results
    - ./target/scala-2.10/:/tmp/app/target/scala-2.10/

worker:
  image: gettyimages/spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  environment:
    SPARK_CONF_DIR: /conf
#    SPARK_WORKER_CORES: 2
#    SPARK_WORKER_MEMORY: 6g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081
  volumes:
    - ./conf/worker:/conf

kafka:
  image: wurstmeister/kafka
  ports:
    - 9092
  expose:
    - 9092
  links:
    - zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.192.134
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - 2181:2181
  expose:
    - 2181
